Repository einsteinpy/einsteinpy, pull requests merged in 2019-04, with the labels that each got.

#169 fixes #168
  src/einsteinpy/tests/test_metric/test_kerr.py
  src/einsteinpy/tests/test_metric/test_schwarzschild.py
Labels: in progress

#159 Warn users when import sympy which is not installed
  src/einsteinpy/tests/test_utils/test_christoffel.py
  src/einsteinpy/utils/christoffel.py
Labels: 1 - In Progress

#176 Add Coordinates Module and Tests
  docs/source/api/coordinates/coordinates_index.rst
  docs/source/api/coordinates/core.rst
  docs/source/api/coordinates/velocity.rst
  docs/source/api/index.rst
  src/einsteinpy/coordinates/__init__.py
  src/einsteinpy/coordinates/core.py
  src/einsteinpy/coordinates/velocity.py
  src/einsteinpy/tests/test_coordinates/test_coord_transform.py
  src/einsteinpy/tests/test_coordinates/test_velocity_transform.py
  src/einsteinpy/utils/bl_coord_transforms.py
  src/einsteinpy/utils/coord_transforms.py
Labels: 2 - Ready

#177 Add animated plots for ScatterGeodesicsPlotter.
  src/einsteinpy/plotting/geodesics_scatter.py
  src/einsteinpy/tests/test_plotting/test_scattergeodesicplotter.py
Labels: 2 - Ready

#195 Add example notebook for scatter geodesics animation.
  docs/source/examples/Animations_in_EinsteinPy.ipynb
  docs/source/examples/scatter_animation.gif
  docs/source/jupyter.rst
  index.ipynb
  src/einsteinpy/plotting/geodesics_scatter.py
Labels: 1 - In Progress

#193 Metric related docs
  docs/source/_static/metric/EFE.PNG
  docs/source/index.rst
  docs/source/metric.rst
Labels: 0 - init

#196 Reorder parameters within functions
  docs/source/examples/Visualizing_event_horizon_and_ergosphere_of_Kerr_black_hole.ipynb
  src/einsteinpy/metric/kerr.py
  src/einsteinpy/metric/kerrnewman.py
  src/einsteinpy/metric/schwarzschild.py
  src/einsteinpy/plotting/geodesics_static.py
  src/einsteinpy/tests/test_metric/test_kerr.py
  src/einsteinpy/tests/test_metric/test_schwarzschild.py
  src/einsteinpy/tests/test_utils/test_kerr_utils.py
  src/einsteinpy/tests/test_utils/test_kerrnewman_utils.py
  src/einsteinpy/tests/test_utils/test_schwarzschild_utils.py
  src/einsteinpy/utils/__init__.py
  src/einsteinpy/utils/kerr_utils.py
  src/einsteinpy/utils/kerrnewman_utils.py
  src/einsteinpy/utils/schwarzschild_utils.py
Labels: 2 - Ready

#157 Add the colors parameter and radius scale
  docs/source/api/plotting/geodesics_scatter.rst
  docs/source/api/plotting/geodesics_static.rst
  docs/source/api/plotting/plotting_index.rst
  src/einsteinpy/plotting/geodesics_scatter.py
  src/einsteinpy/plotting/geodesics_static.py
  src/einsteinpy/tests/test_plotting/test_staticgeodesicplotter.py
Labels: 2 - Ready
