Repository einsteinpy/einsteinpy, pull requests merged in 2021-01, with the labels that each got.

#547 __all__ added
  CHANGELOG
  src/einsteinpy/bodies.py
  src/einsteinpy/constant.py
  src/einsteinpy/coordinates/__init__.py
  src/einsteinpy/examples.py
  src/einsteinpy/geodesic/__init__.py
  src/einsteinpy/hypersurface/__init__.py
  src/einsteinpy/ijit.py
  src/einsteinpy/integrators/__init__.py
  src/einsteinpy/metric/__init__.py
  src/einsteinpy/plotting/__init__.py
  src/einsteinpy/plotting/geodesic/static.py
  src/einsteinpy/rays/__init__.py
  src/einsteinpy/symbolic/__init__.py
  src/einsteinpy/units.py
  tests/test_ijit/test_ijit_without_numba.py
Labels: 2 - Ready

#551 CoordinateError class implemented
  CHANGELOG
  docs/source/api/utils/exceptions.rst
  docs/source/api/utils/utils_index.rst
  src/einsteinpy/coordinates/differential.py
  src/einsteinpy/metric/base_metric.py
  src/einsteinpy/metric/kerr.py
  src/einsteinpy/metric/kerrnewman.py
  src/einsteinpy/metric/schwarzschild.py
  src/einsteinpy/utils/__init__.py
  src/einsteinpy/utils/exceptions.py
  tests/test_coordinates/test_diff_transform.py
  tests/test_metric/test_base_metric.py
  tests/test_utils/test_exceptions.py
Labels: 2 - Ready

#554 Fixes #545 - Addition of Auto-Assign Bot
  .github/auto_assign.yml
Labels: development

#566 Updated einsteinpy.symbolic Jupyter Notebooks
  CHANGELOG
  docs/source/examples/Einstein Tensor symbolic calculation.ipynb
  docs/source/examples/Lambdify symbolic calculation.ipynb
  docs/source/examples/Playing with Contravariant and Covariant Indices in Tensors(Symbolic).ipynb
  docs/source/examples/Predefined Metrics in Symbolic Module.ipynb
  docs/source/examples/Ricci Tensor and Scalar Curvature symbolic calculation.ipynb
  docs/source/examples/Symbolic Module - Christoffel Symbols and Riemann Curvature Tensor.ipynb
  docs/source/examples/Symbolic Module - Einstein Tensor.ipynb
  docs/source/examples/Symbolic Module - Lambdify.ipynb
  docs/source/examples/Symbolic Module - Predefined Metrics.ipynb
  docs/source/examples/Symbolic Module - Ricci Tensor and Scalar Curvature.ipynb
  docs/source/examples/Symbolic Module - Tensor Indexing.ipynb
  docs/source/examples/Symbolic Module - Weyl Tensor.ipynb
  docs/source/examples/Symbolically Understanding Christoffel Symbol and Riemann Curvature Tensor using EinsteinPy.ipynb
  docs/source/examples/Weyl Tensor symbolic calculation.ipynb
  docs/source/jupyter.rst
Labels: 2 - Ready, documentation, symbolic

#568 Update README.rst by changing a single text in the Try it out URL
  README.rst
Labels: 2 - Ready, documentation

#571 Updated Master to Main
  CHANGELOG
  CONTRIBUTING.rst
  README.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: 2 - Ready, documentation
